package entities;
// Generated 11 ene 2025, 18:05:00 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

	private int numDpto;
	private String nombreDpto;
	private Set empleadoses = new HashSet(0);

	public Departamentos() {
	}

	public Departamentos(int numDpto, String nombreDpto) {
		this.numDpto = numDpto;
		this.nombreDpto = nombreDpto;
	}

	public Departamentos(int numDpto, String nombreDpto, Set empleadoses) {
		this.numDpto = numDpto;
		this.nombreDpto = nombreDpto;
		this.empleadoses = empleadoses;
	}

	public int getNumDpto() {
		return this.numDpto;
	}

	public void setNumDpto(int numDpto) {
		this.numDpto = numDpto;
	}

	public String getNombreDpto() {
		return this.nombreDpto;
	}

	public void setNombreDpto(String nombreDpto) {
		this.nombreDpto = nombreDpto;
	}

	public Set getEmpleadoses() {
		return this.empleadoses;
	}

	public void setEmpleadoses(Set empleadoses) {
		this.empleadoses = empleadoses;
	}

}
